namespace Mart.Customer.Api.Contracts.Customers;

public sealed record CreateCustomerRequest(
    string? CustomerCode,
    string? FirstName,
    string? LastName,
    string? DisplayName,
    string MobileNumber,
    string? Email,
    string? Gender,
    DateTime? DateOfBirth,
    string? AddressLine1,
    string? AddressLine2,
    string? City,
    string? State,
    string? Country,
    string? PinCode,
    string? PreferredLanguage,
    string? RegistrationSource,
    bool IsMobileVerified,
    bool IsEmailVerified,
    bool IsActive,
    bool IsBlocked,
    DateTime? LastLoginOn,
    DateTime? CreatedOn,
    DateTime? ModifiedOn);
